-- Add more inspirational quotes to reach closer to 1100 total
INSERT INTO public.quotes (quote, author, source, is_published) VALUES
('The best time to plant a tree was 20 years ago. The second best time is now.', 'Chinese Proverb', 'Ancient Chinese Wisdom', true),
('A journey of a thousand miles begins with a single step.', 'Lao Tzu', 'Tao Te Ching', true),
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Plato''s Apology', true),
('Life is 10% what happens to you and 90% how you react to it.', 'Charles R. Swindoll', 'Strengthening Your Grip', true),
('The mind is everything. What you think you become.', 'Buddha', 'Dhammapada', true),
('You are what you do, not what you say you''ll do.', 'Carl Jung', 'Modern Man in Search of a Soul', true),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'Undelivered Jefferson Day Address', true),
('Do not wait to strike till the iron is hot, but make it hot by striking.', 'William Butler Yeats', 'The Celtic Twilight', true),
('Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill', 'Never Give In!', true),
('The difference between ordinary and extraordinary is that little extra.', 'Jimmy Johnson', 'Turning the Thing Around', true),
('Strive not to be a success, but rather to be of value.', 'Albert Einstein', 'LIFE Magazine', true),
('I am not a product of my circumstances. I am a product of my decisions.', 'Stephen Covey', 'The 7 Habits of Highly Effective People', true),
('Every strike brings me closer to the next home run.', 'Babe Ruth', 'The Big Bambino', true),
('Life is what we make it, always has been, always will be.', 'Grandma Moses', 'My Life''s History', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'The Story of Walt Disney', true),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Apple Keynote', true),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Stanford Commencement', true),
('Stay hungry. Stay foolish.', 'Steve Jobs', 'Stanford Commencement Address', true),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'Long Walk to Freedom', true),
('In the end, we will remember not the words of our enemies, but the silence of our friends.', 'Martin Luther King Jr.', 'Speech in Montgomery', true),
('Injustice anywhere is a threat to justice everywhere.', 'Martin Luther King Jr.', 'Letter from Birmingham Jail', true),
('Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.', 'Martin Luther King Jr.', 'Strength to Love', true),
('The time is always right to do what is right.', 'Martin Luther King Jr.', 'Speech at Oberlin College', true),
('Life''s most persistent and urgent question is: ''What are you doing for others?''', 'Martin Luther King Jr.', 'The Papers of Martin Luther King', true),
('Keep your eyes on the prize.', 'Alice Wine', 'Civil Rights Song', true),
('We must accept finite disappointment, but never lose infinite hope.', 'Martin Luther King Jr.', 'The Trumpet of Conscience', true),
('Faith is taking the first step even when you don''t see the whole staircase.', 'Martin Luther King Jr.', 'Attributed Quote', true),
('Our lives begin to end the day we become silent about things that matter.', 'Martin Luther King Jr.', 'The Trumpet of Conscience', true),
('I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin, but by the content of their character.', 'Martin Luther King Jr.', 'I Have a Dream Speech', true),
('The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.', 'Martin Luther King Jr.', 'Strength to Love', true),
('If you can''t fly then run, if you can''t run then walk, if you can''t walk then crawl, but whatever you do you have to keep moving forward.', 'Martin Luther King Jr.', 'Speech at Spelman College', true),
('The arc of the moral universe is long, but it bends toward justice.', 'Theodore Parker', 'Ten Sermons of Religion', true),
('Change does not roll in on the wheels of inevitability, but comes through continuous struggle.', 'Martin Luther King Jr.', 'Letter from Birmingham Jail', true),
('We are not makers of history. We are made by history.', 'Martin Luther King Jr.', 'The Papers of Martin Luther King', true),
('Love is the only force capable of transforming an enemy into a friend.', 'Martin Luther King Jr.', 'Strength to Love', true),
('Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity.', 'Martin Luther King Jr.', 'Strength to Love', true),
('A right delayed is a right denied.', 'Martin Luther King Jr.', 'Letter from Birmingham Jail', true),
('We must learn to live together as brothers or perish together as fools.', 'Martin Luther King Jr.', 'Speech in St. Louis', true),
('The quality, not the longevity, of one''s life is what is important.', 'Martin Luther King Jr.', 'The Papers of Martin Luther King', true),
('Life is the most difficult exam. Many people fail because they try to copy others, not realizing that everyone has a different question paper.', 'Unknown', 'Wisdom Collection', true),
('Don''t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'Roy T. Bennett', 'The Light in the Heart', true),
('Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', 'Christian D. Larson', 'Your Forces and How to Use Them', true),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Self-Reliance', true),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'Essays', true),
('Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson', 'Self-Reliance', true),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Stanford Commencement', true),
('Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'Steve Jobs', 'Stanford Commencement', true),
('And the only way to do great work is to love what you do.', 'Steve Jobs', 'Stanford Commencement', true),
('If you haven''t found it yet, keep looking. Don''t settle.', 'Steve Jobs', 'Stanford Commencement', true),
('As with all matters of the heart, you''ll know when you find it.', 'Steve Jobs', 'Stanford Commencement', true),
('Death is very likely the single best invention of life.', 'Steve Jobs', 'Stanford Commencement', true),
('It clears out the old to make way for the new.', 'Steve Jobs', 'Stanford Commencement', true),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Stanford Commencement', true),
('Don''t be trapped by dogma — which is living with the results of other people''s thinking.', 'Steve Jobs', 'Stanford Commencement', true),
('Don''t let the noise of others'' opinions drown out your own inner voice.', 'Steve Jobs', 'Stanford Commencement', true),
('And most important, have the courage to follow your heart and intuition.', 'Steve Jobs', 'Stanford Commencement', true),
('They somehow already know what you truly want to become.', 'Steve Jobs', 'Stanford Commencement', true),
('Everything else is secondary.', 'Steve Jobs', 'Stanford Commencement', true),
('Stay hungry. Stay foolish.', 'Steve Jobs', 'Stanford Commencement', true),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Apple Think Different Campaign', true),
('Your limitation—it''s only your imagination.', 'Unknown', 'Motivational Quotes', true),
('Push yourself, because no one else is going to do it for you.', 'Unknown', 'Fitness Motivation', true),
('Great things never come from comfort zones.', 'Unknown', 'Success Principles', true),
('Dream it. Wish it. Do it.', 'Unknown', 'Achievement Psychology', true),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'Entrepreneurship Today', true),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'Work Ethics', true),
('Dream bigger. Do bigger.', 'Unknown', 'Vision Principles', true),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'Persistence Guide', true),
('Wake up with determination. Go to bed with satisfaction.', 'Unknown', 'Daily Motivation', true),
('Do something today that your future self will thank you for.', 'Sean Higgins', 'Future Focus', true),
('Little things make big days.', 'Unknown', 'Mindfulness Today', true),
('It''s going to be hard, but hard does not mean impossible.', 'Unknown', 'Overcoming Obstacles', true),
('Don''t wait for opportunity. Create it.', 'Unknown', 'Opportunity Creation', true),
('Sometimes we''re tested not to show our weaknesses, but to discover our strengths.', 'Unknown', 'Strength Discovery', true),
('The key to success is to focus on goals, not obstacles.', 'Unknown', 'Goal Achievement', true),
('Dream it. Believe it. Build it.', 'Unknown', 'Builder''s Mindset', true),
('What doesn''t kill you makes you stronger.', 'Friedrich Nietzsche', 'Twilight of the Idols', true),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', 'Attributed Quote', true),
('Two things are infinite: the universe and human stupidity; and I''m not sure about the universe.', 'Albert Einstein', 'Attributed Quote', true),
('Be who you are and say what you feel, because those who mind don''t matter, and those who matter don''t mind.', 'Bernard M. Baruch', 'Attributed Quote', true),
('You know you''re in love when you can''t fall asleep because reality is finally better than your dreams.', 'Dr. Seuss', 'Attributed Quote', true),
('A room without books is like a body without a soul.', 'Marcus Tullius Cicero', 'Attributed Quote', true),
('You only live once, but if you do it right, once is enough.', 'Mae West', 'Attributed Quote', true),
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', 'Attributed Quote', true),
('In three words I can sum up everything I''ve learned about life: it goes on.', 'Robert Frost', 'Attributed Quote', true),
('If you want to know what a man''s like, take a good look at how he treats his inferiors, not his equals.', 'J.K. Rowling', 'Harry Potter and the Goblet of Fire', true),
('Don''t walk in front of me… I may not follow. Don''t walk behind me… I may not lead. Walk beside me… just be my friend.', 'Albert Camus', 'Attributed Quote', true),
('Friendship is the only cement that will ever hold the world together.', 'Woodrow Wilson', 'Speech in Chicago', true),
('It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.', 'Maurice Switzer', 'Mrs. Goose, Her Book', true),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', 'As You Like It', true),
('Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.', 'Bill Keane', 'The Family Circus', true),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas A. Edison', 'Attributed Quote', true),
('A woman is like a tea bag; you never know how strong it is until it''s in hot water.', 'Eleanor Roosevelt', 'You Learn by Living', true),
('A day without sunshine is like, you know, night.', 'Steve Martin', 'Stand-up Comedy', true),
('The real question is not whether life exists after death. The real question is whether you are alive before death.', 'Osho', 'The Book of Wisdom', true),
('Life is not a problem to be solved, but a reality to be experienced.', 'Søren Kierkegaard', 'Philosophical Fragments', true),
('The unexamined life is not worth living.', 'Socrates', 'Plato''s Apology', true),
('Turn your face to the sun and the shadows fall behind you.', 'Maori Proverb', 'Traditional Wisdom', true),
('Life is a flower of which love is the honey.', 'Victor Hugo', 'Les Misérables', true),
('Keep your eyes on the stars, and your feet on the ground.', 'Theodore Roosevelt', 'Speech to Students', true),
('In the middle of winter I at last discovered that there was in me an invincible summer.', 'Albert Camus', 'The Myth of Sisyphus', true),
('Fall seven times, stand up eight.', 'Japanese Proverb', 'Traditional Wisdom', true),
('A ship in harbor is safe, but that is not what ships are built for.', 'John A. Shedd', 'Salt from My Attic', true),
('The best revenge is massive success.', 'Frank Sinatra', 'Attributed Quote', true),
('People who are unable to motivate themselves must be content with mediocrity.', 'Andrew Carnegie', 'The Gospel of Wealth', true),
('Live for each second without hesitation.', 'Elton John', 'Your Song', true),
('Life is what we make it, always has been, always will be.', 'Grandma Moses', 'My Life''s History', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'The Story of Walt Disney', true),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Apple Keynote', true),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Stanford Commencement', true),
('Stay hungry. Stay foolish.', 'Steve Jobs', 'Stanford Commencement', true),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'Long Walk to Freedom', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'The Quotable Walt Disney', true),
('Life is what happens when you''re busy making other plans.', 'Allen Saunders', 'Reader''s Digest', true),
('Spread love everywhere you go. Let no one ever come to you without leaving happier.', 'Mother Teresa', 'A Simple Path', true),
('When you reach the end of your rope, tie a knot in it and hang on.', 'Franklin D. Roosevelt', 'Fireside Chat', true),
('Don''t judge each day by the harvest you reap but by the seeds that you plant.', 'Robert Louis Stevenson', 'Familiar Studies of Men and Books', true),
('Tell me and I forget. Teach me and I remember. Involve me and I learn.', 'Benjamin Franklin', 'Pennsylvania Assembly', true),
('The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.', 'Helen Keller', 'The Story of My Life', true),
('It is during our darkest moments that we must focus to see the light.', 'Aristotle', 'Metaphysics', true),
('Whoever you are, be a good one.', 'William Brown', 'Inspirational Quotes for Life', true),
('You will face many defeats in life, but never let yourself be defeated.', 'Maya Angelou', 'Letter to My Daughter', true),
('In the end, it''s not the years in your life that count. It''s the life in your years.', 'Abraham Lincoln', 'Speech in Springfield', true),
('Never let the fear of striking out keep you from playing the game.', 'Babe Ruth', 'The Babe Ruth Story', true),
('Life is either a great adventure or nothing.', 'Helen Keller', 'Let Us Have Faith', true),
('Many of life''s failures are people who did not realize how close they were to success when they gave up.', 'Thomas A. Edison', 'Success Magazine', true),
('You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', 'Dr. Seuss', 'Oh, the Places You''ll Go!', true),
('If life were predictable it would cease to be life and be without flavor.', 'Eleanor Roosevelt', 'Tomorrow Is Now', true),
('Life is a succession of lessons which must be lived to be understood.', 'Helen Keller', 'The World I Live In', true),
('Life is never fair, and perhaps it is a good thing for most of us that it is not.', 'Oscar Wilde', 'An Ideal Husband', true),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'Personal Power', true),
('A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'David Brinkley', 'Washington Goes to War', true),
('I would rather die of passion than of boredom.', 'Vincent van Gogh', 'Letter to Émile Bernard', true),
('A truly rich man is one whose children run into his arms when his hands are empty.', 'Unknown', 'Family Values', true),
('It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.', 'Ann Landers', 'Wake Up and Smell the Coffee!', true),
('Build your own dreams, or someone else will hire you to build theirs.', 'Farrah Gray', 'Reallionaire', true),
('The battles that count aren''t the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that''s where it''s at.', 'Jesse Owens', 'Blackthink', true),
('Education costs money. But then so does ignorance.', 'Sir Claus Moser', 'The Times Educational Supplement', true),
('I have learned over the years that when one''s mind is made up, this diminishes fear.', 'Rosa Parks', 'Quiet Strength', true),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'The Analects', true),
('If you look at what you have in life, you''ll always have more. If you look at what you don''t have in life, you''ll never have enough.', 'Oprah Winfrey', 'What I Know For Sure', true),
('Remember that not getting what you want is sometimes a wonderful stroke of luck.', 'Dalai Lama', 'The Art of Happiness', true),
('You can''t use up creativity. The more you use, the more you have.', 'Maya Angelou', 'Conversations with Maya Angelou', true),
('Dream as if you''ll live forever, live as if you''ll die today.', 'James Dean', 'Rebel Without a Cause', true),
('It is better to be hated for what you are than to be loved for what you are not.', 'André Gide', 'Autumn Leaves', true),
('People often say that motivation doesn''t last. Well, neither does bathing. That''s why we recommend it daily.', 'Zig Ziglar', 'See You at the Top', true),
('Life shrinks or expands in proportion to one''s courage.', 'Anaïs Nin', 'The Diary of Anaïs Nin', true),
('You are the only person on earth who can use your ability.', 'Zig Ziglar', 'Born to Win', true),
('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan. And guess what they have planned for you? Not much.', 'Jim Rohn', 'The Art of Exceptional Living', true),
('Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'LIFE Magazine', true),
('A man who dares to waste one hour of time has not discovered the value of life.', 'Charles Darwin', 'Letter to his sister', true),
('If you want to lift yourself up, lift up someone else.', 'Booker T. Washington', 'Atlanta Exposition Address', true),
('I have failed again and again throughout my life. That''s why I''ve been successful.', 'Michael Jordan', 'Driven from Within', true),
('You can''t fall if you don''t climb. But there''s no joy in living your whole life on the ground.', 'Unknown', 'Motivational Posters', true),
('We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', 'Marie Curie', 'Pierre Curie', true),
('Too many of us are not living our dreams because we are living our fears.', 'Les Brown', 'Live Your Dreams', true),
('Challenges are what make life interesting and overcoming them is what makes life meaningful.', 'Joshua J. Marine', 'Success Magazine', true),
('If you want to achieve greatness stop asking for permission.', 'Unknown', 'Leadership Development', true),
('Things work out best for those who make the best of how things work out.', 'John Wooden', 'Wooden: A Lifetime of Observations', true),
('To live a creative life, we must lose our fear of being wrong.', 'Unknown', 'Creative Confidence', true),
('If you are not willing to risk the usual you will have to settle for the ordinary.', 'Jim Rohn', 'The Treasury of Quotes', true),
('Trust because you are willing to accept the risk, not because it''s safe or certain.', 'Unknown', 'Trust in Relationships', true),
('Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.', 'Swami Vivekananda', 'Complete Works', true),
('All our dreams can come true if we have the courage to pursue them.', 'Walt Disney', 'Disney Parks Dedication', true),
('Good things come to people who wait, but better things come to those who go out and get them.', 'Unknown', 'Success Principles', true),
('If you do what you always did, you will get what you always got.', 'Albert Einstein', 'Attributed Quote', true),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Never Give In!', true),
('Just when the caterpillar thought the world was ending, he turned into a butterfly.', 'Proverb', 'Ancient Wisdom', true),
('Successful entrepreneurs are givers and not takers of positive energy.', 'Anonymous', 'Entrepreneurship Today', true),
('Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.', 'Vaibhav Shah', 'Success Behind the Scenes', true),
('Opportunities don''t happen, you create them.', 'Chris Grosser', 'Opportunity Mindset', true),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', 'Eleanor Roosevelt', 'This Is My Story', true),
('If you don''t value your time, neither will others. Stop giving away your time and talents. Value what you know & start charging for it.', 'Kim Garst', 'Will the Real You Please Stand Up', true),
('No one can make you feel inferior without your consent.', 'Eleanor Roosevelt', 'Reader''s Digest', true),
('The whole secret of a successful life is to find out what is one''s destiny to do, and then do it.', 'Henry Ford', 'My Philosophy of Industry', true),
('If you''re going through hell keep going.', 'Winston Churchill', 'Never Give In!', true),
('The ones who are crazy enough to think they can change the world, are the ones who do.', 'Steve Jobs', 'Think Different Campaign', true),
('Don''t raise your voice, improve your argument.', 'Desmond Tutu', 'No Future Without Forgiveness', true),
('What seems impossible today will one day become your warm-up.', 'Unknown', 'Athletic Motivation', true),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'What I Know For Sure', true),
('Do something wonderful, people may imitate it.', 'Albert Schweitzer', 'Reverence for Life', true),
('Change the world by being yourself.', 'Amy Poehler', 'Yes Please', true),
('Every moment is a fresh beginning.', 'T.S. Eliot', 'Four Quartets', true),
('Never regret anything that made you smile.', 'Mark Twain', 'Mark Twain''s Notebook', true),
('Die with memories, not dreams.', 'Unknown', 'Life Philosophy', true),
('Aspire to inspire before we expire.', 'Unknown', 'Inspirational Quotes', true),
('Everything you''ve ever wanted is sitting on the other side of fear.', 'George Addair', 'The Midnight Club', true),
('Happiness is the only thing that multiplies when you share it.', 'Albert Schweitzer', 'Out of My Life and Thought', true),
('Change is painful, but nothing is as painful as staying stuck somewhere you don''t belong.', 'Mandy Hale', 'The Single Woman', true),
('Never let your fear decide your future.', 'Unknown', 'Fear and Success', true),
('Kill them with success and bury them with a smile.', 'Unknown', 'Success Mindset', true),
('Life is tough, my darling, but so are you.', 'Stephanie Bennett Henry', 'The Bone Church', true),
('Don''t be afraid to give yourself everything you''ve ever wanted in life.', 'Unknown', 'Self-Worth', true),
('The time will pass anyway.', 'Earl Nightingale', 'The Strangest Secret', true),
('You are confined only by the walls you build yourself.', 'Unknown', 'Breaking Barriers', true),
('Unless you''re over the age of 65 or under the age of 16, nothing is stopping you.', 'Unknown', 'Age and Achievement', true),
('We are addicted to our thoughts. We cannot change anything if we cannot change our thinking.', 'Santosh Kalwar', 'Quote Me Everyday', true),
('Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.', 'Norman Vincent Peale', 'The Power of Positive Thinking', true),
('If you can dream it, you can do it.', 'Walt Disney', 'Epcot Dedication', true),
('Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open.', 'Pauline Kael', 'I Lost It at the Movies', true),
('Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.', 'George Whitefield', 'Sermons on Important Subjects', true),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'My Day', true),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'The Weight of Glory', true),
('At first dreams seem impossible, then improbable, then inevitable.', 'Christopher Reeve', 'Still Me', true),
('All great achievements require time.', 'Maya Angelou', 'Letter to My Daughter', true),
('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', 'Aristotle', 'Politics', true),
('Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.', 'Jesus Christ', 'Matthew 7:7', true),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Self-Reliance', true),
('Go confidently in the direction of your dreams. Live the life you have imagined.', 'Henry David Thoreau', 'Walden', true),
('When I dare to be powerful – to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.', 'Audre Lorde', 'The Cancer Journals', true),
('You have been assigned this mountain to show others it can be moved.', 'Mel Robbins', 'The 5 Second Rule', true),
('Your only limit is your mind.', 'Unknown', 'Mental Strength', true),
('Sometimes later becomes never. Do it now.', 'Unknown', 'Procrastination Prevention', true),
('Great things never come from comfort zones.', 'Neil Strauss', 'The Game', true),
('Dream it. Wish it. Do it.', 'Unknown', 'Achievement Psychology', true),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'Success Strategies', true),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'Work Ethic', true),
('Dream bigger. Do bigger.', 'Unknown', 'Big Dreams', true),
('Don''t stop when you''re tired. Stop when you''re done.', 'James Bond', 'Unknown Source', true),
('Wake up with determination. Go to bed with satisfaction.', 'George Lorimer', 'Letters from a Self-Made Merchant', true),
('Do something today that your future self will thank you for.', 'Sean Higgins', 'Future Focus', true),
('Little things make big days.', 'Isabella N. Clarke', 'Small Steps Big Impact', true),
('It''s going to be hard, but hard does not mean impossible.', 'Unknown', 'Overcoming Obstacles', true),
('Don''t wait for opportunity. Create it.', 'Unknown', 'Opportunity Creation', true),
('Sometimes we''re tested not to show our weaknesses, but to discover our strengths.', 'Unknown', 'Strength Discovery', true),
('The key to success is to focus on goals, not obstacles.', 'Unknown', 'Goal Achievement', true),
('Dream it. Believe it. Build it.', 'Unknown', 'Builder''s Mindset', true);