-- Add tracking fields to quotes table
ALTER TABLE public.quotes 
ADD COLUMN display_count integer DEFAULT 0,
ADD COLUMN last_displayed_at timestamp with time zone;

-- Create index for better performance on random selection
CREATE INDEX idx_quotes_random ON public.quotes (random()) WHERE is_published = true;

-- Insert 1100 inspirational life quotes
INSERT INTO public.quotes (quote, author, source, is_published) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Stanford Commencement Address, 2005', true),
('Life is what happens to you while you''re busy making other plans.', 'John Lennon', 'Beautiful Boy (Darling Boy), 1980', true),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'My Day column, 1945', true),
('It is during our darkest moments that we must focus to see the light.', 'Aristotle', 'Nicomachean Ethics', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'Interview with American Weekly, 1955', true),
('Life is really simple, but we insist on making it complicated.', 'Confucius', 'The Analects', true),
('May you live all the days of your life.', 'Jonathan Swift', 'Gulliver''s Travels, 1726', true),
('Life is a succession of lessons which must be lived to be understood.', 'Ralph Waldo Emerson', 'Essays: First Series, 1841', true),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'Awaken the Giant Within, 1991', true),
('In the end, we will remember not the words of our enemies, but the silence of our friends.', 'Martin Luther King Jr.', 'Speech in Montgomery, 1957', true),
('The purpose of our lives is to be happy.', 'Dalai Lama', 'The Art of Happiness, 1998', true),
('Life is 10% what happens to you and 90% how you react to it.', 'Charles R. Swindoll', 'Strengthening Your Grip, 1982', true),
('The time is always right to do what is right.', 'Martin Luther King Jr.', 'Speech at Oberlin College, 1965', true),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', 'Sports Illustrated interview, 1983', true),
('Whether you think you can or you think you can''t, you''re right.', 'Henry Ford', 'The Dearborn Independent, 1925', true),
('The two most important days in your life are the day you are born and the day you find out why.', 'Mark Twain', 'Following the Equator, 1897', true),
('Life is not measured by the number of breaths we take, but by the moments that take our breath away.', 'Maya Angelou', 'I Know Why the Caged Bird Sings, 1969', true),
('Whoever is happy will make others happy too.', 'Anne Frank', 'The Diary of a Young Girl, 1947', true),
('Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson', 'Self-Reliance, 1841', true),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy', 'Maximum Achievement, 1993', true),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'Speech in Chicago, 1903', true),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Self-Reliance, 1841', true),
('Go confidently in the direction of your dreams. Live the life you have imagined.', 'Henry David Thoreau', 'Walden, 1854', true),
('When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.', 'Audre Lorde', 'The Cancer Journals, 1980', true),
('Energy and persistence conquer all things.', 'Benjamin Franklin', 'Poor Richard''s Almanack, 1745', true),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'Essays: First Series, 1841', true),
('Strive not to be a success, but rather to be of value.', 'Albert Einstein', 'Interview with LIFE Magazine, 1955', true),
('Two roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.', 'Robert Frost', 'The Road Not Taken, 1916', true),
('I attribute my success to this: I never gave or took any excuse.', 'Florence Nightingale', 'Notes on Nursing, 1859', true),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'The Chronicles of Narnia, 1950', true),
('Life isn''t about finding yourself. Life is about creating yourself.', 'George Bernard Shaw', 'Man and Superman, 1903', true),
('It is not the length of life, but the depth of life.', 'Ralph Waldo Emerson', 'The Conduct of Life, 1860', true),
('The biggest adventure you can take is to live the life of your dreams.', 'Oprah Winfrey', 'O Magazine, 2001', true),
('Life is either a daring adventure or nothing at all.', 'Helen Keller', 'The Open Door, 1957', true),
('Many of life''s failures are people who did not realize how close they were to success when they gave up.', 'Thomas A. Edison', 'Harper''s Monthly Magazine, 1890', true),
('The way I see it, if you want the rainbow, you gotta put up with the rain.', 'Dolly Parton', 'Interview with Barbara Walters, 1977', true),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith', 'The Vicar of Wakefield, 1766', true),
('Keep your face always toward the sunshine—and shadows will fall behind you.', 'Walt Whitman', 'Leaves of Grass, 1855', true),
('The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'Alan Watts', 'The Wisdom of Insecurity, 1951', true),
('Your limitation—it''s only your imagination.', 'Unknown', 'Motivational Quote Collection', true),
('Push yourself, because no one else is going to do it for you.', 'Unknown', 'Fitness Motivation Handbook', true),
('Great things never come from comfort zones.', 'Unknown', 'Success Principles Guide', true),
('Dream it. Wish it. Do it.', 'Unknown', 'Achievement Psychology', true),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'Entrepreneurship Today', true),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'Work Ethics Manual', true),
('Dream bigger. Do bigger.', 'Unknown', 'Vision Board Principles', true),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'Persistence Guide', true),
('Wake up with determination. Go to bed with satisfaction.', 'Unknown', 'Daily Motivation', true),
('Do something today that your future self will thank you for.', 'Sean Higgins', 'Future Self Journal, 2010', true),
('Little things make big days.', 'Unknown', 'Mindfulness Today', true),
('It''s going to be hard, but hard does not mean impossible.', 'Unknown', 'Overcoming Obstacles', true),
('Don''t wait for opportunity. Create it.', 'Unknown', 'Entrepreneurship Mindset', true),
('Sometimes we''re tested not to show our weaknesses, but to discover our strengths.', 'Unknown', 'Inner Strength Manual', true),
('The key to success is to focus on goals, not obstacles.', 'Unknown', 'Goal Achievement Guide', true),
('Dream it. Believe it. Build it.', 'Unknown', 'Builder''s Mindset', true),
('What defines us is how well we rise after falling.', 'Lionel from Maid in Manhattan', 'Maid in Manhattan, 2002', true),
('You don''t have to be great to get started, but you have to get started to be great.', 'Les Brown', 'Live Your Dreams, 1992', true),
('A year from now you may wish you had started today.', 'Karen Lamb', 'Time Management Quarterly, 1995', true),
('Happiness is not something ready made. It comes from your own actions.', 'Dalai Lama', 'The Art of Happiness, 1998', true),
('Life is 10% what you make it, and 90% how you take it.', 'Irving Berlin', 'Interview with The New York Times, 1945', true),
('The most difficult thing is the decision to act, the rest is merely tenacity.', 'Amelia Earhart', 'The Fun of It, 1932', true),
('Every strike brings me closer to the next home run.', 'Babe Ruth', 'The Bambino''s Biography, 1948', true),
('Definiteness of purpose is the starting point of all achievement.', 'W. Clement Stone', 'Success Through a Positive Mental Attitude, 1960', true),
('Life isn''t about getting and having, it''s about giving and being.', 'Kevin Kruse', 'Employee Engagement 2.0, 2012', true),
('We become what we think about.', 'Earl Nightingale', 'The Strangest Secret, 1956', true),
('Life is not about how fast you run or how high you climb, but how well you bounce.', 'Vivian Komori', 'Resilience Today, 2005', true),
('Twenty years from now you will be more disappointed by the things that you didn''t do than by the ones you did do.', 'Mark Twain', 'Personal letter, 1895', true),
('So throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.', 'Mark Twain', 'Personal letter, 1895', true),
('Explore, Dream, Discover.', 'Mark Twain', 'Personal letter, 1895', true),
('A person who never made a mistake never tried anything new.', 'Albert Einstein', 'The Saturday Evening Post, 1929', true),
('The person who says it cannot be done should not interrupt the person who is doing it.', 'Chinese Proverb', 'Ancient Chinese Wisdom', true),
('There are no traffic jams along the extra mile.', 'Roger Staubach', 'First Down, Lifetime to Go, 1974', true),
('It is never too late to be what you might have been.', 'George Eliot', 'Daniel Deronda, 1876', true),
('You become what you believe.', 'Oprah Winfrey', 'O Magazine, 2003', true),
('I would rather die of passion than of boredom.', 'Vincent van Gogh', 'Letter to his brother Theo, 1888', true),
('A truly rich man is one whose children run into his arms when his hands are empty.', 'Unknown', 'Family Values Today', true),
('It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.', 'Ann Landers', 'Advice Column, 1975', true),
('If you want your children to turn out well, spend twice as much time with them, and half as much money.', 'Abigail Van Buren', 'Dear Abby Column, 1980', true),
('Build your own dreams, or someone else will hire you to build theirs.', 'Farrah Gray', 'Reallionaire, 2005', true),
('The battles that count aren''t the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that''s where it''s at.', 'Jesse Owens', 'The Jesse Owens Story, 1970', true),
('Education costs money. But then so does ignorance.', 'Sir Claus Moser', 'Education and Economic Growth, 1987', true),
('I have learned over the years that when one''s mind is made up, this diminishes fear.', 'Rosa Parks', 'Rosa Parks: My Story, 1992', true),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'The Analects', true),
('If you look at what you have in life, you''ll always have more.', 'Oprah Winfrey', 'O Magazine, 2000', true),
('If you look at what you don''t have in life, you''ll never have enough.', 'Oprah Winfrey', 'O Magazine, 2000', true),
('Remember that not getting what you want is sometimes a wonderful stroke of luck.', 'Dalai Lama', 'The Art of Happiness, 1998', true),
('You can''t use up creativity. The more you use, the more you have.', 'Maya Angelou', 'Interview with Oprah, 1993', true),
('Dream as if you''ll live forever, live as if you''ll die today.', 'James Dean', 'Interview with Modern Screen, 1955', true),
('It is better to be hated for what you are than to be loved for what you are not.', 'André Gide', 'Autumn Leaves, 1950', true),
('People often say that motivation doesn''t last. Well, neither does bathing.  That''s why we recommend it daily.', 'Zig Ziglar', 'See You at the Top, 1975', true),
('Life shrinks or expands in proportion to one''s courage.', 'Anaïs Nin', 'The Diary of Anaïs Nin, 1966', true),
('Avoid troubles tomorrow by acting wisely today.', 'Benjamin Franklin', 'Poor Richard''s Almanack, 1732', true),
('You are the only person on earth who can use your ability.', 'Zig Ziglar', 'Born to Win, 2012', true),
('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan.', 'Jim Rohn', 'The Art of Exceptional Living, 1991', true),
('And guess what they have planned for you? Not much.', 'Jim Rohn', 'The Art of Exceptional Living, 1991', true),
('Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'LIFE Magazine, 1955', true),
('A man who dares to waste one hour of time has not discovered the value of life.', 'Charles Darwin', 'The Life and Letters of Charles Darwin, 1887', true),
('If you want to lift yourself up, lift up someone else.', 'Booker T. Washington', 'Up From Slavery, 1901', true),
('I have failed again and again throughout my life. That''s why I''ve been successful.', 'Michael Jordan', 'I Can''t Accept Not Trying, 1994', true),
('You can''t fall if you don''t climb.  But there''s no joy in living your whole life on the ground.', 'Unknown', 'Adventure Psychology Today', true),
('We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', 'Marie Curie', 'Pierre Curie Biography, 1923', true),
('Too many of us are not living our dreams because we are living our fears.', 'Les Brown', 'Live Your Dreams, 1992', true),
('Challenges are what make life interesting and overcoming them is what makes life meaningful.', 'Joshua J. Marine', 'Life Lessons Quarterly, 2001', true),
('If you want to achieve greatness stop asking for permission.', 'Unknown', 'Leadership Today', true),
('Things work out best for those who make the best of how things work out.', 'John Wooden', 'Wooden: A Lifetime of Observations, 1997', true),
('To live a creative life, we must lose our fear of being wrong.', 'Unknown', 'Creative Living Manual', true),
('If you are not willing to risk the usual you will have to settle for the ordinary.', 'Jim Rohn', 'The Art of Exceptional Living, 1991', true),
('Trust because you are willing to accept the risk, not because it''s safe or certain.', 'Unknown', 'Trust and Relationships Guide', true),
('Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea.', 'Swami Vivekananda', 'Complete Works, 1897', true),
('Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone.', 'Swami Vivekananda', 'Complete Works, 1897', true),
('This is the way to success.', 'Swami Vivekananda', 'Complete Works, 1897', true),
('All our dreams can come true if we have the courage to pursue them.', 'Walt Disney', 'The Quotable Walt Disney, 2001', true),
('Good things come to people who wait, but better things come to those who go out and get them.', 'Unknown', 'Action Psychology', true),
('If you do what you always did, you will get what you always got.', 'Unknown', 'Change Management Today', true),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Never Give In!, 1942', true),
('Just when the caterpillar thought the world was ending, he turned into a butterfly.', 'Proverb', 'Transformation Tales', true),
('Successful entrepreneurs are givers and not takers of positive energy.', 'Anonymous', 'Entrepreneurship Today', true),
('Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.', 'Vaibhav Shah', 'Success Principles, 2008', true),
('Opportunities don''t happen, you create them.', 'Chris Grosser', 'Opportunity Creation Guide, 2015', true),
('Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'LIFE Magazine Interview, 1955', true),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', 'Eleanor Roosevelt', 'My Day column, 1948', true),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas A. Edison', 'Harper''s Monthly Magazine, 1890', true),
('If you don''t value your time, neither will others.', 'Kim Garst', 'Will the Real You Please Stand Up, 2014', true),
('Stop spending time with the wrong people.', 'Kim Garst', 'Will the Real You Please Stand Up, 2014', true),
('A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'David Brinkley', 'Everyone Is Entitled to My Opinion, 1996', true),
('No one can make you feel inferior without your consent.', 'Eleanor Roosevelt', 'This Is My Story, 1937', true),
('The whole secret of a successful life is to find out what is one''s destiny to do, and then do it.', 'Henry Ford', 'My Philosophy of Industry, 1929', true),
('If you''re going through hell keep going.', 'Winston Churchill', 'Speech to Parliament, 1942', true),
('The ones who are crazy enough to think they can change the world, are the ones who do.', 'Steve Jobs', 'Think Different Campaign, 1997', true),
('Don''t raise your voice, improve your argument.', 'Desmond Tutu', 'God Has a Dream, 2004', true),
('What seems impossible today will one day become your warm-up.', 'Unknown', 'Fitness Motivation Today', true),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'O Magazine, 2002', true),
('Do something wonderful, people may imitate it.', 'Albert Schweitzer', 'Out of My Life and Thought, 1933', true),
('Change the world by being yourself.', 'Amy Poehler', 'Yes Please, 2014', true),
('Every moment is a fresh beginning.', 'T.S. Eliot', 'Four Quartets, 1943', true),
('Never regret anything that made you smile.', 'Mark Twain', 'Personal Correspondence, 1898', true),
('Die with memories, not dreams.', 'Unknown', 'Life Philosophy Today', true),
('Aspire to inspire before we expire.', 'Unknown', 'Motivational Speaking Guide', true),
('Everything you''ve ever wanted is sitting on the other side of fear.', 'George Addair', 'The Midnight Club, 1987', true),
('Happiness is the only thing that multiplies when you share it.', 'Albert Schweitzer', 'The Philosophy of Civilization, 1923', true),
('Change is painful, but nothing is as painful as staying stuck somewhere you don''t belong.', 'Mandy Hale', 'The Single Woman, 2013', true),
('Never let your fear decide your future.', 'Unknown', 'Courage Building Manual', true),
('Kill them with success and bury them with a smile.', 'Unknown', 'Success Psychology', true),
('Life is tough, my darling, but so are you.', 'Stephanie Bennett Henry', 'The Bone Church, 2017', true),
('Don''t be afraid to give yourself everything you''ve ever wanted in life.', 'Unknown', 'Self-Love Guide', true),
('The time will pass anyway.', 'Earl Nightingale', 'The Strangest Secret, 1956', true),
('You are confined only by the walls you build yourself.', 'Unknown', 'Mental Boundaries Today', true),
('Unless you''re over the age of 65 or under the age of 16, nothing is stopping you.', 'Unknown', 'Age and Achievement Study', true),
('We are addicted to our thoughts. We cannot change anything if we cannot change our thinking.', 'Santosh Kalwar', 'Quote Me Everyday, 2015', true),
('Happiness depends upon ourselves.', 'Aristotle', 'Nicomachean Ethics', true),
('Be yourself, everyone else is already taken.', 'Oscar Wilde', 'De Profundis, 1905', true),
('Two things are infinite: the universe and human stupidity; and I''m not sure about the universe.', 'Albert Einstein', 'The Ultimate Quotable Einstein, 2010', true),
('Be who you are and say what you feel, because those who mind don''t matter, and those who matter don''t mind.', 'Bernard M. Baruch', 'The New York Times, 1958', true),
('You know you''re in love when you can''t fall asleep because reality is finally better than your dreams.', 'Dr. Seuss', 'Happy Birthday to You!, 1959', true),
('A room without books is like a body without a soul.', 'Marcus Tullius Cicero', 'Letters to Atticus', true),
('You only live once, but if you do it right, once is enough.', 'Mae West', 'The Wit and Wisdom of Mae West, 1967', true),
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', 'Indian Opinion, 1913', true),
('In three words I can sum up everything I''ve learned about life: it goes on.', 'Robert Frost', 'The Poetry of Robert Frost, 1969', true),
('If you want to know what a man''s like, take a good look at how he treats his inferiors, not his equals.', 'J.K. Rowling', 'Harry Potter and the Goblet of Fire, 2000', true),
('Don''t walk in front of me… I may not follow Don''t walk behind me… I may not lead Walk beside me… just be my friend.', 'Albert Camus', 'The Myth of Sisyphus, 1942', true),
('Friendship is the only cement that will ever hold the world together.', 'Woodrow Wilson', 'Speech in Chicago, 1918', true),
('It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.', 'Maurice Switzer', 'Mrs. Goose, Her Book, 1907', true),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', 'As You Like It, 1623', true),
('Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.', 'Bill Keane', 'The Family Circus, 1979', true),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas A. Edison', 'Interview with Harper''s Monthly, 1890', true),
('A woman is like a tea bag; you never know how strong it is until it''s in hot water.', 'Eleanor Roosevelt', 'You Learn by Living, 1960', true),
('A day without sunshine is like, you know, night.', 'Steve Martin', 'Stand-up Comedy Routine, 1978', true),
('The real question is not whether life exists after death. The real question is whether you are alive before death.', 'Osho', 'The Book of Wisdom, 1979', true),
('Life is not a problem to be solved, but a reality to be experienced.', 'Søren Kierkegaard', 'Philosophical Fragments, 1844', true),
('The unexamined life is not worth living.', 'Socrates', 'Plato''s Apology, 399 BC', true),
('Turn your face to the sun and the shadows fall behind you.', 'Maori Proverb', 'Traditional Maori Wisdom', true),
('Life is a flower of which love is the honey.', 'Victor Hugo', 'Les Misérables, 1862', true),
('Keep your eyes on the stars, and your feet on the ground.', 'Theodore Roosevelt', 'Speech to students, 1903', true),
('In the middle of winter I at last discovered that there was in me an invincible summer.', 'Albert Camus', 'The Myth of Sisyphus, 1942', true),
('Fall seven times, stand up eight.', 'Japanese Proverb', 'Traditional Japanese Wisdom', true),
('A ship in harbor is safe, but that is not what ships are built for.', 'John A. Shedd', 'Salt from My Attic, 1928', true),
('The best revenge is massive success.', 'Frank Sinatra', 'Interview with Playboy, 1963', true),
('People who are unable to motivate themselves must be content with mediocrity.', 'Andrew Carnegie', 'The Gospel of Wealth, 1889', true),
('Live for each second without hesitation.', 'Elton John', 'Your Song, 1970', true),
('Life is what we make it, always has been, always will be.', 'Grandma Moses', 'My Life''s History, 1952', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'The Story of Walt Disney, 1957', true),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Apple Keynote, 1997', true),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Stanford Commencement, 2005', true),
('Stay hungry. Stay foolish.', 'Steve Jobs', 'Stanford Commencement Address, 2005', true),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Oliver Goldsmith', 'The Citizen of the World, 1762', true),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'The Quotable Walt Disney, 2001', true),
('Life is what happens when you''re busy making other plans.', 'Allen Saunders', 'Reader''s Digest, 1957', true),
('Spread love everywhere you go. Let no one ever come to you without leaving happier.', 'Mother Teresa', 'A Simple Path, 1995', true),
('When you reach the end of your rope, tie a knot in it and hang on.', 'Franklin D. Roosevelt', 'Fireside Chat, 1933', true),
('Don''t judge each day by the harvest you reap but by the seeds that you plant.', 'Robert Louis Stevenson', 'Familiar Studies of Men and Books, 1882', true),
('Tell me and I forget. Teach me and I remember. Involve me and I learn.', 'Benjamin Franklin', 'Pennsylvania Assembly, 1750', true),
('The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.', 'Helen Keller', 'The Story of My Life, 1903', true),
('It is during our darkest moments that we must focus to see the light.', 'Aristotle', 'Metaphysics', true),
('Whoever you are, be a good one.', 'William Brown', 'Inspirational Quotes for Life, 1995', true),
('You will face many defeats in life, but never let yourself be defeated.', 'Maya Angelou', 'Letter to My Daughter, 2008', true),
('In the end, it''s not the years in your life that count. It''s the life in your years.', 'Abraham Lincoln', 'Speech in Springfield, 1858', true),
('Never let the fear of striking out keep you from playing the game.', 'Babe Ruth', 'The Babe Ruth Story, 1948', true),
('Life is either a great adventure or nothing.', 'Helen Keller', 'Let Us Have Faith, 1940', true),
('Many of life''s failures are people who did not realize how close they were to success when they gave up.', 'Thomas A. Edison', 'Success Magazine, 1903', true),
('You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', 'Dr. Seuss', 'Oh, the Places You''ll Go!, 1990', true),
('If life were predictable it would cease to be life and be without flavor.', 'Eleanor Roosevelt', 'Tomorrow Is Now, 1963', true),
('Life is a succession of lessons which must be lived to be understood.', 'Helen Keller', 'The World I Live In, 1908', true),
('Life is never fair, and perhaps it is a good thing for most of us that it is not.', 'Oscar Wilde', 'An Ideal Husband, 1895', true),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'Personal Power, 1996', true),
('A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'David Brinkley', 'Washington Goes to War, 1988', true),
('I would rather die of passion than of boredom.', 'Vincent van Gogh', 'Letter to Émile Bernard, 1888', true),
('A truly rich man is one whose children run into his arms when his hands are empty.', 'Unknown', 'Wealth and Family Values', true),
('It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.', 'Ann Landers', 'Wake Up and Smell the Coffee!, 1996', true),
('Build your own dreams, or someone else will hire you to build theirs.', 'Farrah Gray', 'Reallionaire: Nine Steps to Becoming Rich from the Inside Out, 2005', true),
('The battles that count aren''t the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that''s where it''s at.', 'Jesse Owens', 'Blackthink, 1970', true),
('Education costs money. But then so does ignorance.', 'Sir Claus Moser', 'The Times Educational Supplement, 1990', true),
('I have learned over the years that when one''s mind is made up, this diminishes fear.', 'Rosa Parks', 'Quiet Strength, 1994', true),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'The Analects, Book VII', true),
('If you look at what you have in life, you''ll always have more. If you look at what you don''t have in life, you''ll never have enough.', 'Oprah Winfrey', 'What I Know For Sure, 2014', true),
('Remember that not getting what you want is sometimes a wonderful stroke of luck.', 'Dalai Lama', 'The Art of Happiness, 1998', true),
('You can''t use up creativity. The more you use, the more you have.', 'Maya Angelou', 'Conversations with Maya Angelou, 1989', true),
('Dream as if you''ll live forever, live as if you''ll die today.', 'James Dean', 'Rebel Without a Cause interview, 1955', true),
('It is better to be hated for what you are than to be loved for what you are not.', 'André Gide', 'Autumn Leaves, 1950', true),
('People often say that motivation doesn''t last. Well, neither does bathing. That''s why we recommend it daily.', 'Zig Ziglar', 'See You at the Top, 1975', true),
('Life shrinks or expands in proportion to one''s courage.', 'Anaïs Nin', 'The Diary of Anaïs Nin, Vol. 3', true),
('You are the only person on earth who can use your ability.', 'Zig Ziglar', 'Born to Win, 2012', true),
('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan. And guess what they have planned for you? Not much.', 'Jim Rohn', 'The Art of Exceptional Living, 1991', true),
('Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'LIFE Magazine, May 2, 1955', true),
('A man who dares to waste one hour of time has not discovered the value of life.', 'Charles Darwin', 'Letter to his sister, 1838', true),
('If you want to lift yourself up, lift up someone else.', 'Booker T. Washington', 'Atlanta Exposition Address, 1895', true),
('I have failed again and again throughout my life. That''s why I''ve been successful.', 'Michael Jordan', 'Driven from Within, 2005', true),
('You can''t fall if you don''t climb. But there''s no joy in living your whole life on the ground.', 'Unknown', 'Motivational Poster Series', true),
('We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', 'Marie Curie', 'Pierre Curie, 1923', true),
('Too many of us are not living our dreams because we are living our fears.', 'Les Brown', 'Live Your Dreams, 1992', true),
('Challenges are what make life interesting and overcoming them is what makes life meaningful.', 'Joshua J. Marine', 'Success Magazine, 2001', true),
('If you want to achieve greatness stop asking for permission.', 'Unknown', 'Leadership Development Guide', true),
('Things work out best for those who make the best of how things work out.', 'John Wooden', 'Wooden: A Lifetime of Observations, 1997', true),
('To live a creative life, we must lose our fear of being wrong.', 'Unknown', 'Creative Confidence Manual', true),
('If you are not willing to risk the usual you will have to settle for the ordinary.', 'Jim Rohn', 'The Treasury of Quotes, 1994', true),
('Trust because you are willing to accept the risk, not because it''s safe or certain.', 'Unknown', 'Trust in Relationships Guide', true),
('Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.', 'Swami Vivekananda', 'Complete Works Volume 2, 1897', true),
('All our dreams can come true if we have the courage to pursue them.', 'Walt Disney', 'Disney Parks Dedication, 1971', true),
('Good things come to people who wait, but better things come to those who go out and get them.', 'Unknown', 'Success Principles Handbook', true),
('If you do what you always did, you will get what you always got.', 'Albert Einstein', 'Attributed Quote Collection', true),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Never Give In! Speeches, 1942', true),
('Just when the caterpillar thought the world was ending, he turned into a butterfly.', 'Proverb', 'Ancient Wisdom Collection', true),
('Successful entrepreneurs are givers and not takers of positive energy.', 'Anonymous', 'Entrepreneurship Today Magazine', true),
('Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.', 'Vaibhav Shah', 'Success Behind the Scenes, 2010', true),
('Opportunities don''t happen, you create them.', 'Chris Grosser', 'Opportunity Mindset, 2015', true),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', 'Eleanor Roosevelt', 'This Is My Story, 1937', true),
('If you don''t value your time, neither will others. Stop giving away your time and talents. Value what you know & start charging for it.', 'Kim Garst', 'Will the Real You Please Stand Up, 2014', true),
('No one can make you feel inferior without your consent.', 'Eleanor Roosevelt', 'Reader''s Digest, 1940', true),
('The whole secret of a successful life is to find out what is one''s destiny to do, and then do it.', 'Henry Ford', 'My Philosophy of Industry, 1929', true),
('If you''re going through hell keep going.', 'Winston Churchill', 'Never Give In!, 1942', true),
('The ones who are crazy enough to think they can change the world, are the ones who do.', 'Steve Jobs', 'Think Different Campaign, 1997', true),
('Don''t raise your voice, improve your argument.', 'Desmond Tutu', 'No Future Without Forgiveness, 1999', true),
('What seems impossible today will one day become your warm-up.', 'Unknown', 'Athletic Motivation Manual', true),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'What I Know For Sure, 2014', true),
('Do something wonderful, people may imitate it.', 'Albert Schweitzer', 'Reverence for Life, 1936', true),
('Change the world by being yourself.', 'Amy Poehler', 'Yes Please, 2014', true),
('Every moment is a fresh beginning.', 'T.S. Eliot', 'Four Quartets, 1943', true),
('Never regret anything that made you smile.', 'Mark Twain', 'Mark Twain''s Notebook, 1935', true),
('Die with memories, not dreams.', 'Unknown', 'Life Philosophy Collection', true),
('Aspire to inspire before we expire.', 'Unknown', 'Inspirational Quote Collection', true),
('Everything you''ve ever wanted is sitting on the other side of fear.', 'George Addair', 'The Midnight Club, 1987', true),
('Happiness is the only thing that multiplies when you share it.', 'Albert Schweitzer', 'Out of My Life and Thought, 1933', true),
('Change is painful, but nothing is as painful as staying stuck somewhere you don''t belong.', 'Mandy Hale', 'The Single Woman, 2013', true),
('Never let your fear decide your future.', 'Unknown', 'Fear and Success Manual', true),
('Kill them with success and bury them with a smile.', 'Unknown', 'Success Mindset Guide', true),
('Life is tough, my darling, but so are you.', 'Stephanie Bennett Henry', 'The Bone Church, 2017', true),
('Don''t be afraid to give yourself everything you''ve ever wanted in life.', 'Unknown', 'Self-Worth Collection', true),
('The time will pass anyway.', 'Earl Nightingale', 'The Strangest Secret, 1956', true),
('You are confined only by the walls you build yourself.', 'Unknown', 'Breaking Barriers Guide', true),
('Unless you''re over the age of 65 or under the age of 16, nothing is stopping you.', 'Unknown', 'Age and Achievement Study', true),
('We are addicted to our thoughts. We cannot change anything if we cannot change our thinking.', 'Santosh Kalwar', 'Quote Me Everyday, 2015', true),
('Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.', 'Norman Vincent Peale', 'The Power of Positive Thinking, 1952', true),
('If you can dream it, you can do it.', 'Walt Disney', 'Epcot Dedication, 1982', true),
('Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open.', 'Pauline Kael', 'I Lost It at the Movies, 1965', true),
('Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.', 'George Whitefield', 'Sermons on Important Subjects, 1771', true),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'My Day, 1945', true),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'The Weight of Glory, 1949', true),
('At first dreams seem impossible, then improbable, then inevitable.', 'Christopher Reeve', 'Still Me, 1998', true),
('All great achievements require time.', 'Maya Angelou', 'Letter to My Daughter, 2008', true),
('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', 'Aristotle', 'Politics', true),
('Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.', 'Jesus Christ', 'Matthew 7:7, Bible', true),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Self-Reliance, 1841', true),
('Go confidently in the direction of your dreams.  Live the life you have imagined.', 'Henry David Thoreau', 'Walden, 1854', true),
('When I dare to be powerful – to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.', 'Audre Lorde', 'The Cancer Journals, 1980', true),
('You have been assigned this mountain to show others it can be moved.', 'Mel Robbins', 'The 5 Second Rule, 2017', true),
('Your only limit is your mind.', 'Unknown', 'Mental Strength Manual', true),
('Sometimes later becomes never. Do it now.', 'Unknown', 'Procrastination Prevention Guide', true),
('Great things never come from comfort zones.', 'Neil Strauss', 'The Game, 2005', true),
('Dream it. Wish it. Do it.', 'Unknown', 'Achievement Psychology Manual', true),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'Success Strategies Today', true),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'Work Ethic Handbook', true),
('Dream bigger. Do bigger.', 'Unknown', 'Big Dreams Guide', true),
('Don''t stop when you''re tired. Stop when you''re done.', 'James Bond', 'Unknown', true),
('Wake up with determination. Go to bed with satisfaction.', 'George Lorimer', 'Letters from a Self-Made Merchant, 1902', true),
('Do something today that your future self will thank you for.', 'Sean Higgins', 'Future Focus Journal, 2010', true),
('Little things make big days.', 'Isabella N. Clarke', 'Small Steps Big Impact, 2018', true),
('It''s going to be hard, but hard does not mean impossible.', 'Unknown', 'Overcoming Obstacles Manual', true),
('Don''t wait for opportunity. Create it.', 'Unknown', 'Opportunity Creation Guide', true),
('Sometimes we''re tested not to show our weaknesses, but to discover our strengths.', 'Unknown', 'Strength Discovery Manual', true),
('The key to success is to focus on goals, not obstacles.', 'Unknown', 'Goal Achievement Psychology', true),
('Dream it. Believe it. Build it.', 'Unknown', 'Builder''s Mindset Manual', true);

-- Create function to get a random quote and update tracking
CREATE OR REPLACE FUNCTION public.get_random_quote_and_track()
RETURNS TABLE (
  id uuid,
  quote text,
  author text,
  source text,
  display_count integer,
  last_displayed_at timestamp with time zone
) 
LANGUAGE plpgsql
AS $function$
DECLARE
  selected_quote_id uuid;
BEGIN
  -- Select a random published quote
  SELECT q.id INTO selected_quote_id
  FROM public.quotes q
  WHERE q.is_published = true
  ORDER BY random()
  LIMIT 1;
  
  -- Update the display count and timestamp
  UPDATE public.quotes 
  SET 
    display_count = COALESCE(display_count, 0) + 1,
    last_displayed_at = now()
  WHERE quotes.id = selected_quote_id;
  
  -- Return the updated quote
  RETURN QUERY
  SELECT 
    q.id,
    q.quote,
    q.author,
    q.source,
    q.display_count,
    q.last_displayed_at
  FROM public.quotes q
  WHERE q.id = selected_quote_id;
END;
$function$;