// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuxkewzwwqccdmoxetit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1eGtld3p3d3FjY2Rtb3hldGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTkyMzYsImV4cCI6MjA3MTI5NTIzNn0.1MXozeh9Av7plOUP1TKN2H2dARHfHRRUxDpxLMC6gNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});